apiVersion: v1
kind: Pod
metadtaa:
  name: postgres-app-pod
  labels:
    name: postgres-app-pod
    app: demo-voting-app
specs:
  containers:
    - name: postgres-app
      image: postgres:9.4
      ports:
        - containerPort: 5432