apiVersion: v1
kind: Pod
metadtaa:
  name: redis-app-pod
  labels:
    name: redis-app-pod
    app: demo-voting-app
specs:
  containers:
    - name: redis-app
      image: redis
      ports:
        - containerPort: 6379