apiVersion: v1
kind: Pod
metadtaa:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
specs:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80