apiVersion: v1
kind: Pod
metadtaa:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
specs:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80