apiVersion: v1
kind: Pod
metadtaa:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
specs:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker